### ISSUE TITLE
Cmake cannot find mingw32-winpthreads

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1073]
#### Description of Problem:
Cmake cannot find mingw32-winpthreads

#### OpenSCAP Version:
master

#### Operating System & Version:
Fedora 28

#### Steps to Reproduce:

1. mingw32-cmake -DENABLE_PYTHON3=FALSE -DENABLE_PROBES=FALSE -DENABLE_OSCAP_UTIL_DOCKER=FALSE ../
2. 
3. 

#### Actual Results:
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindThreads.cmake:232 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:116 (find_package)

#### Expected Results:
Build compiles

**Comment by jan-cerny** [comment]
This will be tricky. I have added a custom `FindThreads` CMake module that allows CMake to find winpthreads build by Vcpkg in order to compile OpenSCAP in Visual Studio 2017.

It looks like this change has broken the cross-compilation.

I think that you can hack it by removing `FindThreads.cmake` from `cmake` directory. Then CMake will use the built-in (system) module instead.

**Comment by redhatrises** [comment]
@jan-cerny would adding the following be acceptable:

```
if(NOT MINGW)
find_package(Threads REQUIRED)
endif()
```

**Comment by jan-cerny** [comment]
@redhatrises I don't think so. I think that would work only if you build OpenSCAP without probes and probe subsystem.

I think we need to look into `cmake/FindThreads.cmake` file instead.
There is a variable `THREADS_USE_PTHREADS_WIN32`, which is used in root CMakeLists.txt around line 115.

Try something like:
```
if(NOT MINGW)
   set(THREADS_USE_PTHREADS_WIN32 true)
endif()
```

If that does not help, we will most likely need to dive into `cmake/FindThreads.cmake` .

**Comment by vivekhegde7** [comment]
> This will be tricky. I have added a custom `FindThreads` CMake module that allows CMake to find winpthreads build by Vcpkg in order to compile OpenSCAP in Visual Studio 2017.
> 
> It looks like this change has broken the cross-compilation.
> 
> I think that you can hack it by removing `FindThreads.cmake` from `cmake` directory. Then CMake will use the built-in (system) module instead.

What need to be edit if I building by Vcpkg in VS2017.

**Comment by vivekhegde7** [comment]
where should I add variable THREADS_PTHREADS_WIN32_LIBRARY and path for pthread lib
can someone help here.

**Comment by redhatrises** [comment]
> where should I add variable THREADS_PTHREADS_WIN32_LIBRARY and path for pthread lib
> can someone help here.

Make sure to use the master branch as it is the only supported branch with Windows support. Now, since you are using Vcpkg, this ticket is not applicable as this ticket is for building on linux with mingw32.

**Comment by vivekhegde7** [comment]
> This will be tricky. I have added a custom `FindThreads` CMake module that allows CMake to find winpthreads build by Vcpkg in order to compile OpenSCAP in Visual Studio 2017.
> 
> It looks like this change has broken the cross-compilation.
> 
> I think that you can hack it by removing `FindThreads.cmake` from `cmake` directory. Then CMake will use the built-in (system) module instead.



INCLUDE(FindPackageHandleStandardArgs)
IF(_Threads_ptwin32)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(Threads DEFAULT_MSG
    THREADS_PTHREADS_WIN32_LIBRARY THREADS_PTHREADS_INCLUDE_DIR)
ELSE()
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(Threads DEFAULT_MSG Threads_FOUND)
ENDIF()

what to change in  FindThreads.cmake.. error pointing to the above mentioned lines.
Or can anybody share custom FindThreads ?

**Comment by evgenyz** [comment]
It looks like this problem was fixed by #1495. At least I can't reproduce it on F31.

**Comment by carlosmmatos** [comment]
All - this is still an issue when trying to cross compile openscap on Fedora 29-32.. This is what I'm getting following the https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc#building-openscap-for-windows-on-a-linux-box-cross-compilation guide:

`-- Found ZLIB: /usr/i686-w64-mingw32/sys-root/mingw/bin/zlib1.dll (found version "1.2.11")
CMake Error at CMakeLists.txt:151 (find_package):
  Could not find a package configuration file provided by "pthread" with any
  of the following names:

    pthreadConfig.cmake
    pthread-config.cmake

  Add the installation prefix of "pthread" to CMAKE_PREFIX_PATH or set
  "pthread_DIR" to a directory containing one of the above files.  If
  "pthread" provides a separate development package or SDK, be sure it has
  been installed.
`

Trying to get this working in order to test building SCAP Workbench on Windows since this is a dependency.

**Comment by evgenyz** [comment]
I'll look at it once again. Can you please also provide a full log of the build? (attach it to the comment).

**Comment by carlosmmatos** [comment]
@evgeni Will do. I'm submitting a PR now, I can probably just add it there for reference.
